# NUMPY

https://docs.scipy.org/doc/numpy-1.14.0/reference/index.html

## Elementwise operations

In [77]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [79]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

###### Comparisons:

In [83]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

###### Computing sums

In [84]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [85]:
x = np.array([1, 3, 2])
x.min()

1

In [86]:
x.max()

3

In [89]:
# index of minimum
x.argmin()  

0

In [90]:
# index of maximum
x.argmax()  

1

###### Logical operations

In [91]:
np.all([True, True, False])

False

In [93]:
a = np.zeros((100, 100))
np.any(a != 0)

False

In [94]:
np.all(a == a)

True

In [95]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

## Indexing and Slicing

In [76]:
a = np.arange(10000)
%timeit a + 1  

l = range(10000)
%timeit [i+1 for i in l] 


7.34 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
794 µs ± 22.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Array indexing

Numpy offers several ways to index into arrays.


### Slicing: 
Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [71]:
import numpy as np

In [72]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11,12]])

In [73]:
a.shape

(4, 3)

In [8]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
b=np.array([0,2,0,1])

# Boolean array indexing: 

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this 
type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [10]:
import numpy as np

In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [12]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
bool_idx = (a > 2)     # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [14]:
print (a[bool_idx])

[3 4 5 6]


In [15]:
print(a[a > 2])     # Prints "[3 4 5 6]"

[3 4 5 6]


# Use of OPERATORS

AND , OR and NOT

| = OR
& = Concatenate
~ = Not


# What is AXIS  in Array

axis = 0    :-  Stand for Rows
axis = 1    :-  Stand for Columns

In [31]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
col_sum = y.sum(axis=1)    # #commulative sum of each column
col_sum

array([ 6, 22, 38])

In [33]:
row_sum = y.sum(axis=0)    # #commulative sum of each rows
row_sum

array([12, 15, 18, 21])

In [34]:
com_sum = y.cumsum()     #  #   commulative sum of each values in array
com_sum

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [35]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
y.prod()   #   #  product over all elements


0

In [37]:
row_prod = y.prod(axis =0)
row_prod

array([  0,  45, 120, 231])

In [38]:
col_prod = y.prod(axis = 1)
col_prod

array([   0,  840, 7920])

In [39]:
y


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Transpose

# argmax   and    argmin  and argsort



In [44]:
# We will create a one dimensional array

one = np.array([2,4,6,75,3])
one

array([ 2,  4,  6, 75,  3])

In [45]:
# We want to know what is the INDEX of HIGHEST value in this array
one.argmax()

3

In [46]:
# We want to know what is the least value in this array
one.argmin()

0

In [47]:
# We want the INDEX value of all your data set in ascending order
# here ascending order is ( 2 , 3, 4 , 6 , 75) in same way it give index values
one.argsort()


array([0, 4, 1, 2, 3], dtype=int64)

In [48]:
# Now working with TWO DIMENSIONAL Array
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
y.argmax()   # It will give the INDEX VALUE of the highest value of your dataset


11

In [50]:
y.argmin()

0

In [51]:
#  If we want to know the HIGHEST Value of each COLUMN we will use AXIS
y.argmax(axis=1)

array([3, 3, 3], dtype=int64)

In [52]:
# If we want to know the HIGHEST Value of each ROW
y.argmax(axis = 0 )

array([2, 2, 2, 2], dtype=int64)

In [53]:
y.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [54]:
y.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
y.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Benefit of TWO ARRAY 

###### Benefit of ARRAY over to LIST ( for multiply two list - we need LOOP , however here in ARRAY we can simply - perform ADDITION/SUBTRACT/MULTIPLY/DIVIDE

In [3]:
import numpy as np
x = np.arange(12)

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:

z =x.reshape(3,4)

In [58]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
# Now if we want to ADD  both the array number
z + y

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [60]:
# Now if we want to multiply both the array number 
z * y

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# SQUARE ROOT

In [61]:
np.sqrt(z)   #   just give your array name in bracket - and it will give you Square Root of your array VALUES

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [62]:
z.sum()   #  It will give you sum of all values

66

In [63]:
z.min()   # it will give you MINIMUM value of you array 

0

In [64]:
z.max() # it will give MAX value of your array

11

In [65]:
z.argsort(axis = 0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]], dtype=int64)

###  WHERE Statement in NUMPY Array

In [66]:
# If we want to know where is my desired value - (it will give you the index values in TUPLE)
np.where(z>5)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [67]:
type(np.where(z>5))

tuple

###   COUNT NON ZERO VALUES

In [68]:
np.count_nonzero(z)   # It will give you count of NON ZERO values in your array

11

In [69]:
np.nonzero(z)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

## All NUMPY -  Methods and Attributes 

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html

In [70]:
z.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])