# Array Dimensions , Indexing and Slicing

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr[0]

###### 1D Array

In [35]:
my_arr = np.array([1,2,4])
my_arr

array([1, 2, 4])

In [36]:
my_arr.ndim

1

In [37]:
my_arr.shape

(3,)

In [7]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
arr[0]

1

In [10]:
print('Shape of Array : ' , arr.shape)
print('Dimension of Array : ', arr.ndim)

Shape of Array :  (3,)
Dimension of Array :  1


###### 2D Array 

In [39]:
arr= np.array([[1,2,3], [1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [42]:
arr = np.array([[1,2,3],[4,5,6],[4,5,6],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [43]:
print('Shape of Array : ' , arr.shape)
print('Dimension of Array : ', arr.ndim)

Shape of Array :  (4, 3)
Dimension of Array :  2


###### 3D Array

In [28]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
x = arr[1][0][1]
x

8

In [33]:
print('Shape of Array : ' , arr.shape)
print('Dimension of Array : ', arr.ndim)

Shape of Array :  (2, 2, 3)
Dimension of Array :  3


In [ ]:
arr = np.array([1,2,3])
arr
arr.ndim
print('Shape of Array " ' , arr.shape)

###### Important Point : All elements of an array should be same size

In [47]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
print('Shape of Array : ' , arr.shape)
print('Dimension of Array : ', arr.ndim)

Shape of Array :  (2, 2, 3)
Dimension of Array :  3


In [50]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,'a']]])
arr

C:\Users\acer\AppData\Local\Temp/ipykernel_8200/32627161.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,'a']]])


array([[list([1, 2, 3]), list([4, 5, 6])],
       [list([7, 8, 9]), list([10, 'a'])]], dtype=object)

### Updating or Changing the Array Elements

In [57]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr[1][0][1]

8

In [53]:
arr[1][0][1]=80
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7, 80,  9],
        [10, 11, 12]]])

In [55]:
arr[0] = 6

In [56]:
arr

array([[[ 6,  6,  6],
        [ 6,  6,  6]],

       [[ 7, 80,  9],
        [10, 11, 12]]])

In [58]:
arr[0] = arr[1]
arr

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

###### Assignment Array Elements in New Variable 

In [62]:
# Incorrect way of assignment to a variable
a = arr[1]
a=12

In [61]:
arr

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
# Correct way of assignment to a variable
a = arr[1]
a[:]=9
arr

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 9,  9,  9],
        [ 9,  9,  9]]])

###### Creating Copy of Array and updating the array elements

In [70]:
arr3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
# Creating a new variable
new_arr = arr3D[1]
new_arr

array([[ 7,  8,  9],
       [10, 11, 12]])

In [72]:
# Updating the new variable elements, but it will impact on main array 
new_arr[:]= 0
arr3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [73]:
# First Create a Copy of main Array and then update the new variable elements
arr3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
new_arr= arr3D[1].copy()

In [74]:
new_arr

array([[ 7,  8,  9],
       [10, 11, 12]])

In [75]:
new_arr[:]=0
new_arr

array([[0, 0, 0],
       [0, 0, 0]])

In [76]:
# Main Array value will be same - No change after creating a variable with COPY method
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Array Indexing

In [77]:
arr3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3D[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr3D[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [79]:
arr3D[1][0]

array([7, 8, 9])

In [80]:
arr3D[1][0][2]

9