# Basic Numpy Function

NumPy is a Python library used for working with arrays.

NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. 

NumPy stands for Numerical Python

##### Checking NumPy Version

In [2]:
import numpy as np
print(np.__version__)

1.20.3


## Array Creation

##  Common mechanisms for creating arrays:

array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile

### Numpy Array with List/Tuple etc

In [3]:
# Creating a List 
my_list = [2,3,6,8,9]

In [4]:
import numpy as np
my_array = np.array(my_list)
my_array

array([2, 3, 6, 8, 9])

In [5]:
type(my_array)

numpy.ndarray

###  Numpy Array with inbuilt function (arange,ones,zeros, full etc.)

In [6]:
# 12 = From where you want to start range
# 30 = Till what value you want range (it will give one less then 30)
# 4 = Its like a step in VBA Loop - it will jump the next number by 4 

my_range = np.arange(12,30,4)
my_range

array([12, 16, 20, 24, 28])

In [7]:
my_ones = np.ones((3,5))
my_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
my_zeros = np.zeros((5,5))
my_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
import numpy as np 
np.empty(2)

array([-4.63634567e+221,  1.57515882e-073])

In [10]:
# Create a constant array
my_full = np.full((2,5),3)  
my_full

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
#The function linspace returns evenly spaced numbers over a specified interval. 
#For example, the below function returns four equally spaced numbers between the interval 0 and 10.
my_linspace= np.linspace(0, 3, num=4)
my_linspace

array([0., 1., 2., 3.])

In [12]:
# numpy.empty(shape, dtype=float, order='C', *, like=None)
# Return a new array of given shape and type, without initializing entries.
my_empty = np.empty(3)
my_empty

array([1., 2., 3.])

##### Creating One Dimensional Array

In [13]:
One_d_array = np.array((1,5,5))
One_d_array

array([1, 5, 5])

In [14]:
# Checking number of dimension in an array
One_d_array.ndim

1

In [15]:
type(One_d_array)

numpy.ndarray

In [16]:
One_d_array.shape

(3,)

##### Creating Two Dimensional Array with List

In [17]:
Two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
Two_d_array
type(Two_d_array)
print(Two_d_array.shape)

(2, 3)


In [18]:
Two_d_array.ndim

2

#### Creating Two Dimensional Array with inbuilt function

In [19]:
One_d_array = np.arange(20)
One_d_array
print('Type of array " ' , type(One_d_array))
print('Number of Dimension in array : ' , One_d_array.ndim)

Type of array "  <class 'numpy.ndarray'>
Number of Dimension in array :  1


In [20]:
 #If you only use the arange function, it will output a one-dimensional array. To make it a two-dimensional array, chain its output with the reshape function.
array = np.arange(20).reshape(4,5)
array    

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
print('Type of array  ' , type(array))
print('Number of Dimension in array : ' , array.ndim)
print('Shape of array : ' , array.shape)

Type of array   <class 'numpy.ndarray'>
Number of Dimension in array :  2
Shape of array :  (4, 5)


##### Creating a Three-dimensional Array and Beyond

In [22]:
#Just a word of caution: The number of elements in the array (27) must be the product of its dimensions (3*3*3). 
#To cross-check if it is a three-dimensional array, you can use the shape property.
array = np.arange(30).reshape(3,5,2)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [23]:
print('Type of array  ' , type(array))
print('Number of Dimension in array : ' , array.ndim)
print('Shape of array : ' , array.shape)

Type of array   <class 'numpy.ndarray'>
Number of Dimension in array :  3
Shape of array :  (3, 5, 2)


###### Creating multi dimensional array

In [24]:
import numpy as np

In [25]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [20,30]])
arr3

C:\Users\acer\AppData\Local\Temp/ipykernel_14000/3263303661.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [20,30]])


array([[list([1, 2]), list([3, 4])],
       [list([5, 6]), list([7, 8])],
       [20, 30]], dtype=object)

In [26]:
arr3.shape

(3, 2)

In [27]:
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [28]:
my_array

array([2, 3, 6, 8, 9])

### ndim

###### To verify the dimensionality of this array, use the ndim property.

In [47]:
my_array

array([2, 3, 6, 8, 9])

In [48]:
my_array.ndim

1

### Shape

###### To verify the shape/size of the array, use the shape property.

In [49]:
my_array.shape

(5,)

In [32]:
my_zeros = np.zeros((5,2))
my_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
my_zeros.shape

(5, 2)

### Differences between python's numpy.ndarray and list datatypes

#### Comparison between Numpy array and Python List

In [52]:
import numpy as np
# importing system module
import sys

S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))

# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))

# declaring a Numpy array of 1000 elements
D= np.arange(1000)

# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)


Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


##### Time comparison between Numpy array and Python list

In [54]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# capturing time before the multiplication of Python lists
initialTime = time.time()

# multiplying elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists to perform multiplication:",
	(time.time() - initialTime),
	"seconds")

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays to perform multiplication:",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists to perform multiplication: 0.19702768325805664 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0029926300048828125 seconds


##### Conclusion
Advantages of using Numpy Arrays Over Python Lists:

#### Why Use NumPy?

#### Other Methods with an Array

In [56]:
array= np.arange(40)
array=array.reshape(4,5,2)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [57]:
#Tuple of bytes to step in each dimension when traversing an array.
array.strides

(40, 8, 4)

In [58]:
# Number of elements in the array.
array.size

40

In [59]:
# Length of one array element in bytes
array.itemsize

4

In [60]:
# Total bytes consumed by the elements of the array.
array.nbytes

160

In [65]:
array= np.arange(40)
array=array.reshape(4,5,2)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [42]:
#The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it)
np.ravel(array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [43]:
# identity() function
# The identity array is a square array with ones on the main diagonal. The identity() function return the identity array.
# Syntax :- numpy.identity(n, dtype=None)
identify = np.identity(6)
identify

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [66]:
#  It will TRANSPOSE your dataset (Be carefull - it is case sensative and need to use CAP T)
array.transpose()

array([[[ 0, 10, 20, 30],
        [ 2, 12, 22, 32],
        [ 4, 14, 24, 34],
        [ 6, 16, 26, 36],
        [ 8, 18, 28, 38]],

       [[ 1, 11, 21, 31],
        [ 3, 13, 23, 33],
        [ 5, 15, 25, 35],
        [ 7, 17, 27, 37],
        [ 9, 19, 29, 39]]])

In [45]:
# It will also TRANSPOSE your dataset
array.T

array([[[ 0, 10, 20, 30],
        [ 2, 12, 22, 32],
        [ 4, 14, 24, 34],
        [ 6, 16, 26, 36],
        [ 8, 18, 28, 38]],

       [[ 1, 11, 21, 31],
        [ 3, 13, 23, 33],
        [ 5, 15, 25, 35],
        [ 7, 17, 27, 37],
        [ 9, 19, 29, 39]]])

In [64]:
# Check the data type of an array
array.dtype

dtype('int32')